CREATE TABLE user(
Id INTEGER GENERATED BY DEFAULT AS IDENTITY,
username varchar(20) NOT NULL,
password varchar(20) default NULL,
sex varchar(2)default null,
phone varchar(11)default NULL,
birth date default null,
PRIMARY KEY (Id)
)

insert into user(username,password,sex,phone,birth)
values('zhang','111','男','18612345678','2018-06-20');
